
        
        
        function setNewImage()
         { document.getElementById("img1").src= "image2.jpg" ;}
        
        function setOldImage()
        { document.getElementById("img1").src = "image1.jpg";}   


        function setNewImage()
         { document.getElementById("img2").src= "messiC.jpg" ;}
        
         function setOldImage()
         { document.getElementById("img2").src = "messiA.jpg";}



     
        
            
